### ISSUE TITLE
Attempting to use proxies leads to astiectron permanently freezing

### ISSUE THREAD

**Issue by true-zero** [asticode/go-astilectron#221]
**Reproducible code**

	// Set logger
	l := log.New(log.Writer(), log.Prefix(), log.Flags())

	// Create astilectron
	a, err := astilectron.New(l, astilectron.Options{
		AppName:           "Test",
		BaseDirectoryPath: "example",
	})
	if err != nil {
		l.Fatal(fmt.Errorf("main: creating astilectron failed: %w", err))
	}
	defer a.Close()

	// Handle signals
	a.HandleSignals()

	// Start
	if err = a.Start(); err != nil {
		l.Fatal(fmt.Errorf("main: starting astilectron failed: %w", err))
	}

	// New window
	var w *astilectron.Window
	if w, err = a.NewWindow("http://google.com", &astilectron.WindowOptions{
		Center: astikit.BoolPtr(true),
		Height: astikit.IntPtr(700),
		Width:  astikit.IntPtr(700),
		Proxy: &astilectron.WindowProxyOptions{
			//BypassRules: "",
			//PACScript: "",
			Rules:       "http=127.0.0.1:8888",
		},*/
	}); err != nil {
		l.Fatal(fmt.Errorf("main: new window failed: %w", err))
	}

	// Create windows
	if err = w.Create(); err != nil {
		l.Fatal(fmt.Errorf("main: creating window failed: %w", err))
	}

	_ = w.OpenDevTools()

	// Blocking pattern
	a.Wait()

This happens even if the struct `WindowProxyOptions` is left completely unfilled.

**Comment by asticode** [comment]
I've pushed a fix that should resolve the issue. Can you use the latest `astilectron` release and let me know whether that fixes your problem ?

**Comment by true-zero** [comment]
The issue was resolved by you fixing that, but I discovered a new bug while using this library so I'm going to open up a new bug report.

**Comment by sinuoy** [comment]
@true-zero somehow it still doesn't work.

If I use `host:port:user:pass` or `user:pass@host:port` webview shows nothing.
If I use `http=host:port:user:pass` or `http=user:pass@host:port` webview shows the result but my own IP address
