### ISSUE TITLE
Unexpected errors after failed initial run

### ISSUE THREAD

**Issue by vivace-io** [asticode/go-astilectron#41]
Canceling the download/extraction for the initial astilectron/electron dependencies returns the following error:

```
provisioning failed: provisioning electron failed: unzipping /path/to/app/vendor/electron-windows-amd64-v1.6.5.zip into /path/to/app/vendor/electron-windows-amd64 failed: opening overall zip reader on /path/to/app/vendor/electron-windows-amd64-v1.6.5.zip failed: zip: not a valid zip file.
```

I would expect that if the process is interrupted at `.Start()` that on the next start it should detect the previous run was interrupted and the extraction directories are not completed that the original zips are deleted, the download restarted. 

In this case, the zips were not completely downloaded when the program was interrupted and quit, thus invalid and the application exited. 

Not really a big issue, just something I noticed while going through the docs of the project.
Thanks for an interesting project. Cheers!

**Comment by asticode** [comment]
@vivace-io nice find! I faced the same problem while developing but I deleted the .zip file instead of fixing it which was lazy and bad. I will fix that!

**Comment by asticode** [comment]
@vivace-io I've pushed a fix, should be all good now.

Does that fix your issue?

**Comment by vivace-io** [comment]
Still experiencing the same issue. I'm not sure if the cleanup on error/cancelled context is getting hit. Again, not a big issue honestly.

The way I'm replicating this is by starting the app, and stopping it a second later. Here's a simplified snippet that I'm running and getting this error.

```
func main() {
	app, err := astilectron.New(astilectron.Options{
		AppName: "Test App",
	})
	if err != nil {
		log.Printf("[FATAL] Failed application setup: %v.", err)
		return
	}
	defer app.Close()
	if err = app.Start(); err != nil {
		log.Printf("[FATAL] Failed application start: %v.", err)
	}
	select {}
}
```

Hope this helps, I'll try to look in to it as well.

**Comment by asticode** [comment]
@vivace-io My apologies, I fixed the problem in the [bundler](https://github.com/asticode/go-astilectron-bundler), not when you use astilectron without using the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) and the [bundler](https://github.com/asticode/go-astilectron-bundler).

Basically, in order to make it work, you have to handle signals on your own. Since what happens is:
- you start the app
- you type `CTRL+C`
- the program is killed without having the opportunity to run the defer functions (and the logic to remove the .zip file if not downloaded completely is in a defer function)

Or you can use the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) that will do that for you :)

**Comment by asticode** [comment]
@vivace-io I forgot that you can allready handle signals in `astilectron` :) Therefore you should be able to do:

```go
func main() {
	app, err := astilectron.New(astilectron.Options{
		AppName: "Test App",
	})
	if err != nil {
		log.Printf("[FATAL] Failed application setup: %v.", err)
		return
	}
	defer app.Close()
        app.HandleSignals()
	if err = app.Start(); err != nil {
		log.Printf("[FATAL] Failed application start: %v.", err)
	}
	app.Wait()
}
```

And that should remove the .zip file if not downloaded completely (however I can't test it right now, I'm relying on my hypotheses :D)

**Comment by vivace-io** [comment]
So `app.HandleSignals()` should cancel that context if sigterm is sent? That's exactly what I was looking for! Thanks.
